// <auto-generated />
using MetadataConfigurationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetadataConfigurationAPI.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20220703141613_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MetadataConfigurationAPI.Models.EntityConfiguration", b =>
                {
                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityName");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("MetadataConfigurationAPI.Models.FieldConfiguration", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"), 1L, 1);

                    b.Property<string>("EntityConfigurationEntityName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.HasKey("FieldId");

                    b.HasIndex("EntityConfigurationEntityName");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("MetadataConfigurationAPI.Models.FieldConfiguration", b =>
                {
                    b.HasOne("MetadataConfigurationAPI.Models.EntityConfiguration", null)
                        .WithMany("Fields")
                        .HasForeignKey("EntityConfigurationEntityName");
                });

            modelBuilder.Entity("MetadataConfigurationAPI.Models.EntityConfiguration", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
